{% set version = "4.0.1" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: assimp
  version: {{ version }}

source:
  url: https://github.com/assimp/assimp/archive/v{{ version }}.tar.gz
  fn:  assimp-{{ version }}.tar.gz
  sha256: 60080d8ab4daaab309f65b3cffd99f19eb1af8d05623fff469b9b652818e286e
  patches:
    - assimp.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
  run:

test:
  

about:
  home: https://github.com/assimp/assimp
  license: BSD 3-Clause
  summary: >
    A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.

extra:
  recipe-maintainers:
    - Linqing Feng
