package:
  {% if NEUTU_TARGET is defined %}
    name: {{NEUTU_TARGET}}
  {% else %}
    name: neutu
  {% endif %}

  {% if GIT_DESCRIBE_NUMBER|int == 0 %}
    version: "{{GIT_DESCRIBE_TAG}}"
  {% else %}
    # If we're using a non-tagged revision, append '.postN' to the version
    version: "{{GIT_DESCRIBE_TAG}}.post{{GIT_DESCRIBE_NUMBER}}"
  {% endif %}

source:
    git_url: ../

build:
  number: 0
  string: {{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  script_env:
   - NEUTU_TARGET

requirements:
  build:
    - gxx_linux-64 # [linux]
    - cmake

  host:
    - qt      5.9*
    - fftw    3.3*
    - jansson 2.7*
    - libpng  1.6*
    - hdf5    1.10*
    - pango   1.40* # [linux64]
    - lowtis  0.1.0.post71*
    - cmake
    - ninja 1.7.2*
    - tbb 2019.4*
    - tbb-devel 2019.4*
    - vtk 8.2.*
    - assimp 4.0.1*
    - glbinding 2.1.3*
    - draco 1.3.4*
    - libarchive 3.3.3*
    - libiconv 1.15*
    - librdkafka 1.0.1*
    - alsa-lib 1.1.5* # [linux64]
    - xorg-libxrandr 1.5.1* # [linux64]
    - xorg-libxcursor 1.2.0* # [linux64]
    - xorg-libxtst 1.2.3* # [linux64]

  run:
    - python  3.7.3*
    - qt      5.9*
    - fftw    3.3*
    - jansson 2.7*
    - libpng  1.6*
    - hdf5    1.10*
    - pango   1.40* # [linux64]
    - lowtis  0.1.0.post71*
    - tbb 2019.4*
    - tbb-devel 2019.4*
    - vtk 8.2.*
    - assimp 4.0.1*
    - glbinding 2.1.3*
    - draco 1.3.4*
    - libarchive 3.3.3*
    - libiconv 1.15*
    - librdkafka 1.0.1*
    - alsa-lib 1.1.5* # [linux64]
    - xorg-libxrandr 1.5.1* # [linux64]
    - xorg-libxcursor 1.2.0* # [linux64]
    - xorg-libxtst 1.2.3* # [linux64]
    - marktips 0.3*

about:
  home: http://github.com/janelia-flyem/NeuTu
  license: GPL
