{% set version = "1.3.5" %}
# {% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: draco
  version: {{ version }}

source:
  url: https://github.com/google/draco/archive/{{ version }}.zip
  fn:  draco-{{ version }}.zip
  #sha256: 12c372610a49f8cc6da6da6511835b24d70cdfa18b2099b5e3e9d6e1c805e23f

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
  run:

test:
  

about:
  home: https://github.com/google/draco
  license: MIT
  summary: >
    Draco is a library for compressing and decompressing 3D geometric meshes and point clouds. It is intended to improve the storage and transmission of 3D graphics.

extra:
  recipe-maintainers:
    - Linqing Feng
