#!/bin/bash
BASEDIR=$(dirname $0)
cd $BASEDIR/c

if [ ! -d obj ]
then
  mkdir obj
fi

if [ ! -d bin ]
then
  mkdir bin
fi

if [ ! -d obj64 ]
then
  mkdir obj64
fi

if [ ! -d release ]
then
  mkdir release
fi

if [ ! -d lib ]
then
  mkdir lib
fi

cdir=`pwd`
allvar=$@
echo $allvar
compile_64bit=0
#compile_shared=0

if [ "$(uname)" == "Darwin" ]; then
  AFLAGS="-D_OPTIONAL_FLAGS -mmacosx-version-min=10.7"
else
  AFLAGS=-D_OPTIONAL_FLAGS
fi

lib_config=lib
force_update=0

all_config_option="--disable-png"

for var in "$@"
do
  is_config_option=1
  if [ $var == "-nopb" ]; then
    AFLAGS=-DINTERFACE_PROGRESS_OFF
    is_config_option=0
  fi
  if [ $var == "--enable-shared" ]; then
    #compile_shared=1
    lib_config=dy$lib_config
  fi
  if [ $var == "--release" ]; then
    lib_config=${lib_config}_release
    is_config_option=0
  fi
  if [ $var == "--force-update" ]
  then
    force_update=1
    is_config_option=0
  fi
  if [ $is_config_option -eq 1 ]
  then
    all_config_option="$all_config_option $var"
  fi
done

arch=`uname -a | sed 's/.*x86_64.*/x86_64/'`

if [ $arch = 'x86_64' ]; then
  all_config_option="$all_config_option --enable-64bit"
fi

if [ $force_update -eq 1 ]
then
  make clean -f configure.makefile
fi
make -f configure.makefile CONFIG_OPTION="$all_config_option"

echo 'updating neurolabi ...'
cd $cdir

if [ $force_update -eq 1 ]
then
  make clean
fi
make $lib_config AFLAGS="$AFLAGS"

#if [ $compile_shared -eq 1 ]; then
#  make dylib AFLAGS="$AFLAGS"
#fi

