#!/bin/bash

dvidlib=/opt/Download/buildem/lib
if [ -d /opt/Download/miniconda/envs/dvidenv ]
then
  dvidlib=/opt/Download/miniconda/envs/dvidenv/lib 
fi

export LD_LIBRARY_PATH=$dvidlib:$LD_LIBRARY_PATH
export PATH=$dvidlib/bin:$PATH
LD_PRELOAD=/usr/lib64/libpython2.7.so gdb -ex 'set environ LD_PRELOAD' --args /opt/Download/neutube/neurolabi/build_debug/neuTube_d
