#!/bin/bash

if [ $# -ne 2 ]
then
  echo './flyem_post_install <neutube_dir> <build_dir>'
  exit 1
fi

neutube_dir=$1
build_dir=$2

cp -r $neutube_dir/neurolabi/gui/doc $build_dir/
if [ $HOSTNAME = emrecon13 ]
then
  cp $neutube_dir/neurolabi/gui/config_flyem_3dfix.xml $neutube_dir/neurolabi/build/config.xml
fi

 
