#!/bin/bash
echo '*****************'
which gcc
master_dir=/groups/flyem/home/zhaot/Work/neutube_ws
source $master_dir/neurolabi/shell/flyem_ntupd
if [ $# -ge 1 ]
then
  install_dir=$1
else
  install_dir=/opt
fi

flyem_neutu_update $1
if [ -d $install_dir/Download/miniconda/envs/dvidenv/include ]
then
  flyem_neutu_update $1 debug
fi


#cd $install_dir/Download/neutube
#/usr/bin/git pull

#condaEnv=$install_dir/Download/miniconda/envs/dvidenv
#if [ -d $install_dir/Download/miniconda/envs/dvidenv/include ]
#then
#  sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q CONDA_ENV=$condaEnv
#  if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
#  then
#    sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q CONDA_ENV=$condaEnv -c debug
#  fi
#else
#  sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q BUILDEM_DIR=$install_dir/Download/buildem
#  if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
#  then
#    sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q BUILDEM_DIR=$install_dir/Download/buildem -c debug
#  fi
#fi

$install_dir/Download/neutube/neurolabi/shell/flyem_post_install $install_dir/Download/neutube $install_dir/Download/neutube/neurolabi/build
if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
then
  $install_dir/Download/neutube/neurolabi/shell/flyem_post_install $install_dir/Download/neutube $install_dir/Download/neutube/neurolabi/build_debug
fi
 
