#!/bin/bash

if [ $# -ne 2 ]
then
  echo './flyem_post_install <neutube_dir> <build_dir>'
  exit 1
fi

neutube_dir=$1
build_dir=$2

if [ $HOSTNAME = emrecon13 ]
then
  cp $neutube_dir/neurolabi/gui/config_flyem_3dfix.xml $build_dir/config.xml
fi
if [ $HOSTNAME = emrecon20 ]
then
  cp $neutube_dir/neurolabi/gui/config_flyem_3dfix.xml $build_dir/config.xml
fi
if [ $HOSTNAME = emrecon22 ]
then
  cp $neutube_dir/neurolabi/gui/config_flyem_3dfix.xml $build_dir/config.xml
fi

if [ -f $neutube_dir/custom/flyem_config.json ]
then
  cp $neutube_dir/custom/flyem_config.json $build_dir/json/flyem_config.json
fi

if [ -f $neutube_dir/custom/config.xml ]
then
  cp $neutube_dir/custom/config.xml $build_dir/config.xml
fi

 
