#!/bin/bash

if [ $# -ge 1 ]
then
  install_dir=$1
else
  install_dir=/opt
fi

echo $PATH

downloadDir=$install_dir/Download
cd $downloadDir
condaDir=$install_dir/Download/miniconda
if [ ! -d $condaDir ]
then
  if [ `uname` = 'Darwin' ]
  then
    curl -O https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
    bash Miniconda-latest-MacOSX-x86_64.sh -b -p $condaDir
  else
    wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    bash Miniconda-latest-Linux-x86_64.sh -b -p $condaDir
  fi
fi

CONDA_ROOT=`$condaDir/bin/conda info --root`
if [ ! -d $condaDir/envs/dvidenv ]
then
  source ${CONDA_ROOT}/bin/activate root
  { echo y; } | $condaDir/bin/conda create -n dvidenv -c flyem libdvid-cpp=0.2.post20
fi

if [ `uname` != 'Darwin' ]
then
  GCCVER=$(gcc --version | grep ^gcc | sed 's/^.* //g')
  if [ $GCCVER \> '4.9.0' ]
  then
    if [ ! -f $condaDir/envs/dvidenv/bin/gcc ]
    then
      source ${CONDA_ROOT}/bin/activate dvidenv
      $condaDir/bin/conda install -c https://conda.anaconda.org/cgat gcc -y
    fi
  fi
fi

