#!/bin/bash
if [ $# -ge 1 ]
then
  install_dir=$1
else
  install_dir=/opt
fi

if [ $# -ge 2 ]
then
  master_dir=$2
else
  master_dir=/groups/flyem/home/zhaot/Work/neutube_ws
  if [ ! -d $master_dir ]
  then
    if [ `uname` == 'Darwin' ]; then
      scriptDir=$(cd $(dirname "$0") && pwd -P)
    else
      scriptDir=$(dirname `readlink -f "$0"`)
    fi
    echo $scriptDir
    master_dir=$(dirname "$(dirname $scriptDir)")
    echo $master_dir
  fi
fi

source $master_dir/neurolabi/shell/flyem_utilities.sh

flyem_neutu_update $install_dir
if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
then
  flyem_neutu_update $install_dir debug
fi


#cd $install_dir/Download/neutube
#/usr/bin/git pull

#condaEnv=$install_dir/Download/miniconda/envs/dvidenv
#if [ -d $install_dir/Download/miniconda/envs/dvidenv/include ]
#then
#  sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q CONDA_ENV=$condaEnv
#  if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
#  then
#    sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q CONDA_ENV=$condaEnv -c debug
#  fi
#else
#  sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q BUILDEM_DIR=$install_dir/Download/buildem
#  if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
#  then
#    sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem -q BUILDEM_DIR=$install_dir/Download/buildem -c debug
#  fi
#fi

$install_dir/Download/neutube/neurolabi/shell/flyem_post_install $install_dir/Download/neutube $install_dir/Download/neutube/neurolabi/build
if [ -d $install_dir/Download/neutube/neurolabi/build_debug ]
then
  $install_dir/Download/neutube/neurolabi/shell/flyem_post_install $install_dir/Download/neutube $install_dir/Download/neutube/neurolabi/build_debug
fi
 
