#!/bin/bash

if [ $# -lt 2 ]
then
  echo './flyem_backup_node <address> <node>'
fi

address=$1
node=$2

http POST http://$address/api/node/$node/commit log:="[\"locked for backup\"]"
date=`date`
http POST http://$address/api/node/$node/branch log:="[\"Production node created at $date\"]"


 
