#!/bin/bash

if test $# -ne 1
then
    echo 'mkshell file'
else
    if [ -f "$1" ]
    then
	echo "warning: file $1 exists"
    else
	echo '#!/bin/bash' > "$1"
	echo ' ' >> "$1"
	chmod a+x "$1"
	echo "$1 created"
    fi
    vim "$1"
fi
