#!/bin/bash

#ssh emrecon2 '/opt/bin/ntupd'

cmd_dir=/groups/flyem/home/zhaot/Work/neutube_ws/neurolabi/shell
src_neutu=/groups/flyem/home/zhaot/Work/neutube_ws

if [ $# -ge 1 ]
then
  ssh $1 "$cmd_dir/ntconfig $src_neutu /opt/Download/neutube"
else
  namelist=""
  while read line
  do
    #echo $line
    name=`echo $line | awk '{$1=$1};1'`
    if [ ! -z $name ]
    then
      if [ ${name:0:1} != "#" ]
      then
        #echo $name
        namelist="$namelist $name"
        #ssh $name "$cmd_dir/ntconfig $src_neutu /opt/Download/neutube"
      fi
    fi
  done < machine.txt
  echo $namelist
  for name in $namelist
  do
    echo $name
    ssh $name "$cmd_dir/ntconfig $src_neutu /opt/Download/neutube"
  done
fi

