#!/bin/bash

ssh emrecon2 '/opt/bin/ntupd'
ssh emrecon10 '/opt/bin/ntupd'
ssh emrecon14 '/opt/bin/ntupd'
ssh emrecon15 '/opt/bin/ntupd'
ssh emrecon17 '/opt/bin/ntupd'
ssh emrecon19 '/opt/bin/ntupd'
ssh emrecon42 '/opt/bin/ntupd'
ssh ordishc-ws1 '/opt/bin/ntupd'

 
