#!/bin/bash
set -e
installDir=$1
downloadDir=$1
condaDir=$downloadDir/miniconda
neutuEnv='neutu-env'

cd $downloadDir
if [ ! -d pyzem ]
then
  git clone https://github.com/janelia-flyem/pyzem.git pyzem
fi
source $condaDir/bin/activate $neutuEnv
cd pyzem
make init
make install
 
