#!/bin/bash

if test $# -eq 0
then
  install_dir=/opt
else
  install_dir=$1
fi
echo "Installing NeuTu under $install_dir"

if [ ! -d $install_dir/bin ]
then
  mkdir $install_dir/bin
fi

downloadDir=$install_dir/Download
if [ ! -d $downloadDir ]
then
  mkdir $downloadDir
fi

if [ ! -f $install_dir/Trolltech/Qt4.8.5/bin/qmake ]
then
  qtsrc='qt-everywhere-opensource-src-4.8.5'
  if [ ! -d $downloadDir/$qtsrc ]
  then
    if [ ! -f $downloadDir/$qtsrc.tar.gz ]
    then
      cp /groups/flyem/home/zhaot/Downloads/$qtsrc.tar.gz $downloadDir
    fi
    cd $downloadDir
    tar -xvf $qtsrc.tar.gz
  fi

  cd $downloadDir/$qtsrc
  { echo o; yes; } | ./configure --prefix=$install_dir/Trolltech/Qt4.8.5 -no-webkit -qt-libpng
  make -j3
  make install
fi

cd $downloadDir

GIT_CMD=/usr/bin/git
if [ -f /usr/local/git/bin/git ]
then
  export PATH=/usr/local/git/bin:$PATH
  GIT_CMD=/usr/local/git/bin/git
fi

if [ ! -d $downloadDir/neutube ]
then
  $GIT_CMD clone /groups/flyem/home/zhaot/Work/neutube_ws/.git neutube
  $GIT_CMD checkout pripublic
fi

if [ ! -d $downloadDir/buildem ]
then
  $GIT_CMD clone http://github.com/janelia-flyem/buildem.git
fi
 
if [ ! -d $downloadDir/libdvid-cpp ]
then
  $GIT_CMD clone https://github.com/janelia-flyem/libdvid-cpp.git
fi

CMAKE_CMD=cmake
if [ -f /usr/local/cmake/bin/cmake ]
then
  CMAKE_CMD=/usr/local/cmake/bin/cmake
fi

cd $downloadDir/libdvid-cpp
$GIT_CMD pull
if [ ! -d build ]
then
  mkdir build
  cd build
  $CMAKE_CMD .. -DBUILDEM_DIR=$downloadDir/buildem
  make
else
  cd build
fi

$CMAKE_CMD .. -DBUILDEM_DIR=$downloadDir/buildem
make
make

updateFile=$install_dir/bin/ntupd
if [ ! -f $updateFile ]
then
  touch $updateFile
  echo '#!/bin/bash' > $updateFile
  echo "cd $downloadDir/neutube" >> $updateFile
  echo "$GIT_CMD pull" >> $updateFile
  if [ -d $downloadDir/buildem ]
  then
    ext_qmake_args="-q BUILDEM_DIR=$downloadDir/buildem"
  fi
  echo "sh build.sh $install_dir/Trolltech/Qt4.8.5/bin/qmake $install_dir/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem $ext_qmake_args" >> $updateFile
  chmod a+x $updateFile
fi

$install_dir/bin/ntupd

run_script=$install_dir/bin/neutu
if [ ! -f $run_script ]
then
  touch $run_script
  echo '#!/bin/bash' > $run_script
  echo "export LD_LIBRARY_PATH=$downloadDir/buildem/lib:$LD_LIBRARY_PATH" >> $run_script
  echo "$downloadDir/neutube/neurolabi/build/neuTube" >> $run_script
  chmod a+x $run_script
fi


