#!/bin/bash

set -e 
if test $# -eq 0
then
  echo './setup_neutu_env <conda_dir> [<env_name>]'
  exit 1
fi

CONDA_DIR=$1
ENV_NAME=${2:-neutu-env}
condarc=$CONDA_DIR/.condarc

if [ ! -f $condarc ]
then
  cp condarc $condarc
fi

source $CONDA_DIR/bin/activate root
conda create -n $ENV_NAME python=2 -y
source $CONDA_DIR/bin/activate $ENV_NAME
conda install --file neutu_conda_requirements.txt -y
if [ `uname` == 'Linux' ]; then
  conda install pango=1.40* -y
fi
./fixqtdebug Qt5 $CONDA_DIR/envs/$ENV_NAME/lib





 
