#!/bin/bash

set -e 

usage() {
  echo ""
  echo "Setup neutu development environment"
  echo "USAGE: $0 <install_dir> [-m <miniconda_folder>] [-e <env>]"
  echo "  install_dir: root installation directory where miniconda is expected to be installed."
  echo "  miniconda_folder: the folder under <install_dir> for installing minico
nda"
  echo "  env: env name for hosting development environment."
  exit 1
}

if test $# -eq 0
then
  usage
fi

install_dir=$1
CONDA_FOLDER=miniconda
ENV_NAME=neutu-dev
shift 1
while getopts m:e: OPTION
do
  case "$OPTION" in
    m)
      CONDA_FOLDER="$OPTARG"
      ;;
    e)
      ENV_NAME="$OPTARG"
      ;;
    *)
      usage
      ;;
  esac
done

condaDir=$install_dir/$CONDA_FOLDER
if [ -d $condaDir ]
then
  echo "WARNING: $condaDir already exists. I'll assume miniconda has been installed as expected and continue."
fi

if [ ! -d $condaDir ]
then
  if [ `uname` = 'Darwin' ]
  then
    curl -X GET https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-MacOSX-x86_64.sh > Miniconda-latest-x86_64.sh
  else
    curl -X GET https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh > Miniconda-latest-x86_64.sh
  fi
  bash Miniconda-latest-x86_64.sh -b -p $condaDir
  #rm -f Miniconda-latest-x86_64.sh
fi

./setup_neutu_env "$condaDir" "$ENV_NAME"

 
