#!/bin/bash

if test $# -eq 0
then
  install_dir=/opt
else
  install_dir=$1
fi
echo "Installing NeuTu under $install_dir"

if [ -f /opt/gcc482/bin/gcc-4.8.2 ]
then
  PATH=/opt/gcc482/bin:$PATH
  echo $PATH
  which gcc
fi

if [ ! -d $install_dir/bin ]
then
  mkdir $install_dir/bin
fi

downloadDir=$install_dir/Download
if [ ! -d $downloadDir ]
then
  mkdir $downloadDir
  chmod a+w $downloadDir
fi

./flyem_setup_linux_conda

if [ ! -f $install_dir/Trolltech/Qt4.8.5/bin/qmake ]
then
  qtsrc='qt-everywhere-opensource-src-4.8.5'
  if [ ! -d $downloadDir/$qtsrc ]
  then
    if [ ! -f $downloadDir/$qtsrc.tar.gz ]
    then
      cp /groups/flyem/home/zhaot/Downloads/$qtsrc.tar.gz $downloadDir
    fi
    cd $downloadDir
    tar -xvf $qtsrc.tar.gz
  fi

  cd $downloadDir/$qtsrc
  { echo o; yes; } | ./configure --prefix=$install_dir/Trolltech/Qt4.8.5 -no-webkit -qt-libpng
  make -j3
  make install
fi


cd $downloadDir

GIT_CMD=/usr/bin/git
if [ -f /usr/local/git/bin/git ]
then
  export PATH=/usr/local/git/bin:$PATH
  GIT_CMD=/usr/local/git/bin/git
fi

master_dir=/groups/flyem/home/zhaot/Work/neutube_ws
if [ ! -d $downloadDir/neutube ]
then
  $GIT_CMD clone $master_dir/.git neutube
  cd $downloadDir/neutube
  $GIT_CMD checkout flyem_release
fi


CMAKE_CMD=cmake
if [ -f /usr/local/cmake/bin/cmake ]
then
  CMAKE_CMD=/usr/local/cmake/bin/cmake
fi


updateFile=$install_dir/bin/ntupd
touch $updateFile
echo '#!/bin/bash' > $updateFile
echo 'master_dir=/groups/flyem/home/zhaot/Work/neutube_ws' >> $updateFile
echo 'if [ $# -eq 1 ]' >> $updateFile
echo 'then' >> $updateFile
echo '  branch=$1' >> $updateFile
echo 'fi' >> $updateFile
echo "cd $downloadDir/neutube" >> $updateFile
echo 'if [ -z $branch ]' >> $updateFile
echo 'then' >> $updateFile
echo "  $GIT_CMD pull" >> $updateFile
echo 'else' >> $updateFile
echo "  $GIT_CMD pull origin \$GIT_CMD" >> $updateFile
echo "fi" >> $updateFile

echo "$downloadDir/neutube/neurolabi/shell/flyem_ntupd $install_dir" >> $updateFile
if [ -f $install_dir/bin/ntupd_post ]
then
  echo "$install_dir/bin/ntupd_post $install_dir" >> $updateFile
fi

chmod a+x $updateFile

$install_dir/bin/ntupd

run_script=$install_dir/bin/neutu
if [ ! -f $run_script ]
then
  touch $run_script
  echo '#!/bin/bash' > $run_script
  echo "dvidlib=/opt/Download/miniconda/envs/dvidenv/lib"
  echo "export LD_LIBRARY_PATH=\$dvidlib:$LD_LIBRARY_PATH" >> $run_script
  echo "$downloadDir/neutube/neurolabi/build/neuTube" >> $run_script
  chmod a+x $run_script
fi


