#!/bin/bash

if [ ! -d /opt/bin ]
then
  mkdir /opt/bin
fi

downloadDir=/opt/Download
if [ ! -d $downloadDir ]
then
  mkdir $downloadDir
fi

if [ ! -f /opt/Trolltech/Qt4.8.5/bin/qmake ]
then
  qtsrc='qt-everywhere-opensource-src-4.8.5'
  if [ ! -d $downloadDir/$qtsrc ]
  then
    if [ ! -f $downloadDir/$qtsrc.tar.gz ]
    then
      cp /groups/flyem/home/zhaot/Downloads/$qtsrc.tar.gz $downloadDir
    fi
    cd $downloadDir
    tar -xvf $qtsrc.tar.gz
  fi

  cd $downloadDir/$qtsrc
  ./configure --prefix=/opt/Trolltech/Qt4.8.5 -no-webkit -qt-libpng
  make -j3
  make install
fi

cd /opt/Download

if [ ! -d /opt/Download/neutube ]
then
  /usr/bin/git clone /groups/flyem/home/zhaot/Work/neutube_ws/.git neutube
  /usr/bin/git checkout pripublic
fi

if [ ! -d /opt/Download/buildem ]
then
  /usr/bin/git clone http://github.com/janelia-flyem/buildem.git
fi
 
if [ ! -d /opt/Download/libdvid-cpp ]
then
  /usr/bin/git clone https://github.com/janelia-flyem/libdvid-cpp.git
fi

cd /opt/Download/libdvid-cpp
if [ ! -d build ]
then
  mkdir build
  cd build
  cmake .. -DBUILDEM_DIR=/opt/Download/buildem
  make
else
  cd build
fi

cmake .. -DBUILDEM_DIR=/opt/Download/buildem
make -j3

updateFile=/opt/bin/ntupd
if [ ! -f $updateFile ]
then
  touch $updateFile
  echo '#!/bin/bash' > $updateFile
  echo 'cd /opt/Download/neutube' >> $updateFile
  echo '/usr/bin/git pull' >> $updateFile
  if [ -d /opt/Download/buildem ]
  then
    ext_qmake_args='-q "BUILDEM_DIR=/opt/Download/buildem"'
  fi
  echo "sh build.sh /opt/Trolltech/Qt4.8.5/bin/qmake /opt/Trolltech/Qt4.8.5/mkspecs/linux-g++ -e flyem $ext_qmake_args" >> $updateFile
  chmod a+x $updateFile
fi

/opt/bin/ntupd

