#!/bin/bash

set -e 

if test $# -eq 0
then
  echo './setup_conda_for_neutu <install_dir>'
  exit 1
fi

install_dir=$1

echo "Installing miniconda under $install_dir"
if [ ! -d $install_dir ]
then
  mkdir -p $install_dir
fi

condaDir=$install_dir/miniconda
if [ -d $condaDir ]
then
  echo "$condaDir already exists. Abort."
  exit 0
fi

condaDir=$install_dir/miniconda
if [ ! -d $condaDir ]
then
  if [ `uname` = 'Darwin' ]
  then
    curl -X GET https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > Miniconda-latest-x86_64.sh
  else
    curl -X GET https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > Miniconda-latest-x86_64.sh
  fi
  bash Miniconda-latest-x86_64.sh -b -p $condaDir
  #rm -f Miniconda-latest-x86_64.sh
fi

./setup_neutu_env $condaDir neutu-env


 
