#!/bin/bash

set -e 
if test $# -eq 0
then
  echo './setup_neutu_env <conda_dir> [<env_name>]'
  exit 1
fi

CONDA_DIR=$1
ENV_NAME=${2:-neutu-env}
condarc=$CONDA_DIR/.condarc
ENV_DIR=$CONDA_DIR/envs/$ENV_NAME

if [ ! -f $condarc ]
then
  cp condarc $condarc
fi

source $CONDA_DIR/bin/activate root
conda create -n $ENV_NAME python=3.6 -y -c flyem-forge/label/upgrade201904 -c conda-forge -c defaults

# Create a special file to tell the conda solver that upgrading/downgrading Qt and Python is forbidden.
# https://conda.io/docs/user-guide/tasks/manage-pkgs.html?highlight=pinned#preventing-packages-from-updating-pinning
/bin/cat <<EOF > ${ENV_DIR}/conda-meta/pinned
python=3*
qt=5*
EOF

source $CONDA_DIR/bin/activate $ENV_NAME
if [ `uname` == 'Linux' ]; then
  conda install --file neutu_conda_requirements_linux.txt -y -c flyem-forge/label/upgrade201904 -c conda-forge -c defaults
else
  conda install --file neutu_conda_requirements_mac.txt -y -c flyem-forge/label/upgrade201904 -c conda-forge -c defaults
fi
./fixqtdebug Qt5 ${ENV_DIR}/lib





 
