#!/bin/bash

if [ $# -ge 1 ]
then
  install_dir=$1
else
  install_dir=/opt
fi

cd $install_dir/Download/libdvid-cpp
/usr/bin/git pull
cd build
cmake .. -DBUILDEM_DIR=$install_dir/Download/buildem
make

