HEADERS +=     test/zswctreetest.h \
    test/ztestheader.h \
    test/zobject3dscantest.h \
    test/zswcpathtest.h \
    test/zgraphtest.h \
    test/zstackgraphtest.h \
    test/zstringtest.h \
    test/zobject3dtest.h \
    test/zswcanalyzertest.h \
    test/zellipsoidtest.h \
    test/zstitchgridtest.h \
    test/zcuboidtest.h \
    test/zflyemqualitycontroltest.h \
    test/zflyemsynaseannotationtest.h \
    test/zstackdoctest.h \
    test/ztreetest.h \
    test/zswctreematchertest.h \
    test/zprogresstest.h \
    test/zswctreenodetest.h \
    test/zhistogramtest.h \
    test/zflyemneuronrangetest.h \
    test/zflyemneuronfiltertest.h \
    test/zjsontest.h \
    test/zswcmetrictest.h \
    test/zmatrixtest.h \
    test/zstacktest.h \
    test/zswcgeneratortest.h \
    test/zflyemneuronimagefactorytest.h \
    test/zspgrowtest.h \
    test/zflyemneuronmatchtest.h \
    test/z3dinteracttest.h \
    test/zvoxelgraphicstest.h \
    test/zdocplayertest.h
