HEADERS += \
    $$PWD/commontest.h \
    $$PWD/flyemutilitiestest.h \
    $$PWD/miscutilitytest.h \
    $$PWD/neutusetest.h \
    $$PWD/taskprotocoltasktest.h \
    $$PWD/zaffinerecttest.h \
    $$PWD/zcolorschemetest.h \
    $$PWD/zdviddialogtest.h \
    $$PWD/zdvidinfotest.h \
    $$PWD/zdvidlabelslicetest.h \
    $$PWD/zdvidtargetfactorytest.h \
    $$PWD/zdvidtargettest.h \
    $$PWD/zdvidurltest.h \
    $$PWD/zflyembodyannotationprotocaltest.h \
    $$PWD/zflyembodycolorschemetest.h \
    $$PWD/zflyembookmarktest.h \
    $$PWD/zlocalneurosegtest.h \
    $$PWD/zmeshtest.h \
    $$PWD/znetworkutilstest.h \
    $$PWD/zneurontracertest.h \
    $$PWD/zstackdocobjectupdatetest.h \
    $$PWD/zswctreetest.h \
    $$PWD/zsttransformtest.h \
    $$PWD/zobject3dscantest.h \
    $$PWD/zswcpathtest.h \
    $$PWD/zgraphtest.h \
    $$PWD/zstackgraphtest.h \
    $$PWD/zstringtest.h \
    $$PWD/zobject3dtest.h \
    $$PWD/zswcanalyzertest.h \
    $$PWD/zellipsoidtest.h \
    $$PWD/zstitchgridtest.h \
    $$PWD/zcuboidtest.h \
    $$PWD/zflyemqualitycontroltest.h \
    $$PWD/zflyemsynaseannotationtest.h \
    $$PWD/zstackdoctest.h \
    $$PWD/ztreetest.h \
    $$PWD/zswctreematchertest.h \
    $$PWD/zprogresstest.h \
    $$PWD/zswctreenodetest.h \
    $$PWD/zhistogramtest.h \
    $$PWD/zflyemneuronrangetest.h \
    $$PWD/zflyemneuronfiltertest.h \
    $$PWD/zjsontest.h \
    $$PWD/zswcmetrictest.h \
    $$PWD/zmatrixtest.h \
    $$PWD/zstacktest.h \
    $$PWD/zswcgeneratortest.h \
    $$PWD/zflyemneuronimagefactorytest.h \
    $$PWD/zspgrowtest.h \
    $$PWD/zflyemneuronmatchtest.h \
    $$PWD/z3dinteracttest.h \
    $$PWD/zvoxelgraphicstest.h \
    $$PWD/zdocplayertest.h \
    $$PWD/zopenvdbtest.h \
    $$PWD/zdvidtest.h \
    $$PWD/zblockgridtest.h \
    $$PWD/zsparsestacktest.h \
    $$PWD/zimagetest.h \
    $$PWD/z3dgraphtest.h \
    $$PWD/zobject3dfactorytest.h \
    $$PWD/zdvidiotest.h \
    $$PWD/zlinesegmenttest.h \
    $$PWD/zclosedcurvetest.h \
    $$PWD/zarraytest.h \
    $$PWD/zflyembodymergertest.h \
    $$PWD/zstackobjectgrouptest.h \
    $$PWD/ztestheader.h \
    $$PWD/zvoxelarraytest.h \
    $$PWD/zdvidannotationtest.h \
    $$PWD/zgradientmagnitudemoduletest.h \
    $$PWD/zflyemproofdoctest.h \
    $$PWD/zflyembodycoloroptiontest.h \
    $$PWD/zresolutiontest.h \
    $$PWD/zdvidroitest.h \
    $$PWD/zflyembody3dtest.h \
    $$PWD/zstackskeletonizertest.h \
    $$PWD/zdvidroitest.h \
    $$PWD/zflyembodyannotationtest.h \
    $$PWD/zviewprojtest.h \
    $$PWD/z3dfiltersettingtest.h \
    $$PWD/zdvidresultservicetest.h \
    $$PWD/zxmltest.h \
    $$PWD/zpointtest.h \
    $$PWD/zwatershedtest.h \
    $$PWD/ztestall.h \
    $$PWD/zstackobjectinfotest.h \
    $$PWD/zglobaltest.h \
    $$PWD/zmouseeventprocessortest.h \
    $$PWD/zpositionmappertest.h \
    $$PWD/zstackdochelpertest.h \
    $$PWD/zgeometrytest.h \
    $$PWD/zdviddataslicetest.h \
    $$PWD/zstackviewparamtest.h \
    $$PWD/zflyembodymanagertest.h \
    $$PWD/zflyemtaskhelpertest.h \
    $$PWD/zflyembodystatustest.h \
    $$PWD/zunittest.h \
    $$PWD/cypherquerytest.h \
    $$PWD/zwidgetmessagetest.h \
    $$PWD/zstackobjecttest.h \
    $$PWD/z3dswcfiltertest.h \
    $$PWD/flyembodyselectionmanagertest.h \
    $$PWD/zinteractivecontexttest.h \
    $$PWD/zdvidenvtest.h \
    $$PWD/zdvidnodetest.h \
    $$PWD/zdvidsparsestacktest.h \
    $$PWD/flyembodyannotationdialogtest.h \
    $$PWD/qtcoretest.h \
    $$PWD/zdvidsynapseannotationdialogtest.h

SOURCES += \
    $$PWD/zunittest.cpp
