#!/bin/bash

currDIR="$( cd -P "$( dirname "$0" )" && pwd )"
version=2.1.3
srcDIR=$currDIR/glbinding-$version

if [ -d $srcDIR ]
then
  rm -rf $srcDIR
fi
cd $currDIR
if [ ! -f glbinding-$version.zip ]
then
  curl -LJOk https://github.com/cginternals/glbinding/archive/v$version.zip
fi
unzip glbinding-$version.zip

buildDIR=$srcDIR/../__glbinding-build
installDIR=$currDIR/glbinding

if [ -d $installDIR ]
then
  rm -rf $installDIR
fi

if [ ! -d $srcDIR ]
then
  echo ERROR: src folder $srcDIR does not exist.
  exit 1 # terminate and indicate error
fi

if [ -d $buildDIR ]
then
  rm -rf $buildDIR
fi
mkdir $buildDIR
cd $buildDIR

cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$installDIR -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DOPTION_BUILD_GPU_TESTS:BOOL="0" -DBUILD_SHARED_LIBS:BOOL="0" -DOPTION_BUILD_TESTS:BOOL="0" -DCMAKE_CXX_FLAGS:STRING="${CMAKE_CXX_FLAGS} -stdlib=libc++ -std=c++11" $srcDIR

ninja install

cd $currDIR
rm -rf $buildDIR
rm -rf $srcDIR
