#!/bin/bash

currDIR="$( cd -P "$( dirname "$0" )" && pwd )"
srcDIR=$currDIR/glbinding-master

if [ -d $srcDIR ]
then
  rm -rf $srcDIR
fi
cd $currDIR
unzip glbinding-master.zip

buildDIR=$srcDIR/../__glbinding-build
installDIR=$currDIR/glbinding
numCores=$( sysctl -n hw.logicalcpu )

if [ -d $installDIR ]
then
  rm -rf $installDIR
fi

if [ ! -d $srcDIR ]
then
  echo ERROR: src folder $srcDIR does not exist.
  exit 1 # terminate and indicate error
fi

if [ -d $buildDIR ]
then
  rm -rf $buildDIR
fi
mkdir $buildDIR
cd $buildDIR

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$installDIR -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DOPTION_BUILD_GPU_TESTS:BOOL="0" -DBUILD_SHARED_LIBS:BOOL="0" -DOPTION_BUILD_TESTS:BOOL="0" -DCMAKE_CXX_FLAGS:STRING="${CMAKE_CXX_FLAGS} -stdlib=libc++ -std=c++11" $srcDIR

make -j $numCores install

cd $currDIR
rm -rf $buildDIR
rm -rf $srcDIR
